import React, { useState } from 'react';
import type { BriefingData } from '../types.ts';
import { sendBriefingEmail } from '../services/emailService';

interface EmailComposerProps {
  data: BriefingData;
}

export const EmailComposer: React.FC<EmailComposerProps> = ({ data }) => {
  const [copied, setCopied] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [sendResult, setSendResult] = useState<'idle' | 'success' | 'error'>('idle');
  
  const recipient = "ambujkr8@gmail.com";

  const subject = `Executive Briefing: Textile & Market Update - ${new Date().toLocaleDateString()}`;
  const body = `
DAILY TEXTILE & FABRIC MARKET BRIEFING
Date: ${new Date().toLocaleDateString()}
----------------------------------------

${data.summary}

----------------------------------------
Sources:
${data.sources.map(s => `- ${s.title}: ${s.uri}`).join('\n')}

Generated by TextileIntel AI
  `.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(body);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleMailTo = () => {
    const mailtoLink = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.location.href = mailtoLink;
  };

  const handleCloudSend = async () => {
    if (!import.meta.env.VITE_EMAILJS_PUBLIC_KEY) {
      alert("EmailJS configuration missing in .env file");
      return;
    }
    
    setIsSending(true);
    setSendResult('idle');
    try {
      await sendBriefingEmail(data);
      setSendResult('success');
      setTimeout(() => setSendResult('idle'), 5000);
    } catch (e) {
      setSendResult('error');
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div className="bg-white border border-stone-200 rounded-xl p-8 shadow-lg mt-8 fade-in-up delay-200">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 gap-4">
        <div>
          <h3 className="text-xl serif font-semibold text-stone-900">Distribution Channel</h3>
          <p className="text-sm text-stone-500 mt-1">Review and dispatch intelligence report.</p>
        </div>
 <div className="flex flex-wrap gap-3">
  {/* Cloud Send Button */}
  <button
    onClick={handleCloudSend}
    disabled={isSending || sendResult === 'success'}
    className={`px-5 py-2.5 rounded-lg text-sm font-medium transition-all duration-300 flex items-center gap-2 border ${
      sendResult === 'success' 
        ? 'bg-emerald-50 text-emerald-700 border-emerald-200' 
        : sendResult === 'error'
        ? 'bg-red-50 text-red-700 border-red-200'
        : 'bg-white text-stone-600 hover:bg-stone-50 border-stone-200 hover:border-stone-300'
    }`}
  >
    {isSending ? "Sending..." : sendResult === 'success' ? "Sent via Cloud" : "Auto-Send Test"}
  </button>

  {/* ✅ COPY EMAIL BUTTON (ADD HERE) */}
  <button
    onClick={handleCopy}
    className="bg-white border border-stone-200 hover:border-stone-300 px-5 py-2.5 rounded-lg text-sm font-medium transition flex items-center gap-2"
  >
    {copied ? "Copied ✓" : "Copy Email"}
  </button>

  {/* Open Mail App Button */}
  <button
    onClick={handleMailTo}
    className="bg-stone-900 hover:bg-black text-white px-5 py-2.5 rounded-lg text-sm font-medium transition-colors shadow-lg shadow-stone-900/10 flex items-center gap-2"
  >
    Open Mail App
  </button>
</div>
              </div>

      
      <div className="bg-stone-50 rounded-lg p-6 font-mono text-xs text-stone-600 border border-stone-200 shadow-inner relative group">
        <div className="mb-3 border-b border-stone-200 pb-2 flex flex-col gap-1">
          <div className="flex items-center">
            <span className="text-stone-400 uppercase tracking-widest text-[10px] w-16">To:</span> 
            <span className="text-stone-900 font-bold bg-yellow-100 px-1 rounded">{recipient}</span>
          </div>
          <div className="flex items-center">
            <span className="text-stone-400 uppercase tracking-widest text-[10px] w-16">Subject:</span> 
            <span className="text-stone-800 truncate">{subject}</span>
          </div>
        </div>
        <div className="whitespace-pre-wrap line-clamp-4 hover:line-clamp-none transition-all cursor-pointer opacity-80 hover:opacity-100">
          {body}
        </div>
        <div className="mt-4 pt-2 border-t border-stone-200 text-center text-stone-400 italic text-[10px]">
          Click body to expand preview
        </div>
      </div>
    </div>
  );
};